### ISSUE TITLE
Cannot find module 'fs-extra' error

### ISSUE THREAD

**Issue by NikeshKhatiwada** [lc-ui/lcui-cli#4]
I installed the tool and created a project with tool. When I tried to run it with `npm run start`, it showed error as: `Error: Cannot find module 'fs-extra'` but I already have the module installed. 
![image](https://user-images.githubusercontent.com/55629421/117283686-bf66c980-ae85-11eb-9848-07b6f191e535.png)
 How do I fix the error?

**Comment by lc-soft** [comment]
```bash
npm run build:css
lcpkg export --filter runtime --arch x64 --mode debug app
lcui build
lcui run
```

**Comment by lc-soft** [comment]
The `npm install` command will install the `fs-extra` module. Have you run it in the `my-project` directory?

**Comment by NikeshKhatiwada** [comment]
> Please try to use the following command instead of `npm run start`:
> 
> ```shell
> npm run build:css
> lcpkg export --filter runtime --arch x64 --mode debug app
> lcui build
> lcui run
> ```

Error:
![image](https://user-images.githubusercontent.com/55629421/117324281-60b64580-aeaf-11eb-88aa-602d6fa258fd.png)

**Comment by lc-soft** [comment]
```bash
npm install
npm run start
```

**Comment by NikeshKhatiwada** [comment]
> ```shell
> npm install
> npm run start
> ```

Error:
![image](https://user-images.githubusercontent.com/55629421/117330944-f228b600-aeb5-11eb-975a-fdf35f097ebe.png)
![image](https://user-images.githubusercontent.com/55629421/117330795-c4dc0800-aeb5-11eb-962f-8d2908f31088.png)

**Comment by lc-soft** [comment]
`node-gyp` uses Python 2. please install Python 2 and try again.

![image](https://user-images.githubusercontent.com/1730073/117387950-5bdbab00-af1c-11eb-9093-a963bb06a565.png)

![image](https://user-images.githubusercontent.com/1730073/117387975-69913080-af1c-11eb-9079-08968779a87c.png)


Or try to specify the binary download address to skip building `node-sass`.
```bash
npm install --sass-binary-site=http://npm.taobao.org/mirrors/node-sass
```

**Comment by NikeshKhatiwada** [comment]
I already have Python 2 installed. Still getting error...
![image](https://user-images.githubusercontent.com/55629421/117471162-4a73bc80-af77-11eb-9ef3-d7f867b2d752.png)
![image](https://user-images.githubusercontent.com/55629421/117471429-90308500-af77-11eb-8573-a6bfb2dbbd57.png)
![image](https://user-images.githubusercontent.com/55629421/117471657-d38af380-af77-11eb-91d8-378acded78af.png)
![image](https://user-images.githubusercontent.com/55629421/117471895-09c87300-af78-11eb-89d1-fbffb951ce31.png)

**Comment by lc-soft** [comment]
I'll take some time to improve this tool and project template to solve these problems. Please wait a few days.

**Comment by NikeshKhatiwada** [comment]
Errors are fixed now. I close the issue.
